### ISSUE TITLE
Hi. Can you add some usage

### ISSUE THREAD

**Issue by 1275741406** [AlexanderLindkjaer/csgoHue#7]
你好 可以补充下用法吗
Hi. Can you add some usage?

我不能拿到游戏返回值
I can't get the game return value 

谢谢
thank

![image](https://user-images.githubusercontent.com/34826954/69927581-660da480-14f3-11ea-9978-3edfb90e0709.png)

**Comment by AlexanderLindkjaer** [comment]
Hi @1275741406 
When does this happen? is it when you boot the app ?

I guess https://192.168.0.1/find is the hue api rest call, being rejected due to CORS.

Maybe they changed their api or maybe it is something in your setup. 
It's been a while since i tried the app, but haven't seen it before. Please let me know if you find a solution or want to make a PR :)

**Comment by 1275741406** [comment]
> Hi @1275741406
> When does this happen? is it when you boot the app ?
> 
> I guess https://192.168.0.1/find is the hue api rest call, being rejected due to CORS.
> 
> Maybe they changed their api or maybe it is something in your setup.
> It's been a while since i tried the app, but haven't seen it before. Please let me know if you find a solution or want to make a PR :)


--------------------------------------------------------------------------------------------------------------
抱歉， 我忽视了hueAPi。
Sorry I ignored hueAPi.

在配置 gamestate_integration_hue.cfg 文件后拿不到游戏数据的问题已经解决。
The data problem has been solved after the ‘gamestate_integration_hue.cfg’ file has been configured.

我昨天不清楚这个项目的代码设计逻辑。
I didn't know the code design logic for this project yesterday.

现在我的项目用到 MIDI code. 技术方案定在了electron+nodeJS。
My project need use  midicode, and I've decided to implement it in electron and nodejs.

你本地的nodeJS版本是多少呢？可以告诉我吗？
What is your local nodeJS version? Can you tell me?

会在这个仓库的基础上进行改进。
Will improve on the basis of this warehouse.

我在中国常使用的邮箱： 13009394726m@sina.cn
Email I use often in China: 13009394726m@sina.cn

谢谢。
thank。
